link:
  home_page: "http://www.railstutorial.org/"
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "https://www.railstutorial.org/book"
  rails_screencast: "https://screencasts.railstutorial.org/"
  rails_ruby: "https://rubyonrails.org/"
  learn_enough: "https://www.learnenough.com/"
