link:
  home_page: "http://www.railstutorial.org/"
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "https://www.railstutorial.org/book"
  rails_contact: "https://www.railstutorial.org/contact"
  rails_screencast: "https://screencasts.railstutorial.org/"
  rails_news: "https://news.railstutorial.org/"
  rails_ruby: "https://rubyonrails.org/"
  learn_enough: "https://www.learnenough.com/"
  michael_hartl: "https://www.michaelhartl.com/"
name:
  length:
    max: 30
email:
  length:
    max: 255
    min: 10
  valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
password:
  length:
    min: 6
avatar:
  size:
    default: 80
    index: 50
    microposts: 50
    user_info: 50
page:
  index: 10
  microposts: 10
  feed: 10
time:
  password_expire: 2
microposts:
  length:
    max: 140
image:
  type: ["image/jpeg", "image/gif", "image/png"]
  type2: "image/jpeg,image/gif,image/png"
  max_size: 5
  resize: [500,500]
